language: cpp
dist: xenial
compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - g++-7
script: 
  - mkdir build && cd build && cmake .. && make -j $(nproc)