language: cpp
dist: xenial

common-sources: &all_sources
  - ubuntu-toolchain-r-test
  - llvm-toolchain-xenial-6.0

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: *all_sources
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: *all_sources
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"        

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: *all_sources
          packages:
            - ['clang-6.0', 'libstdc++-8-dev']
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: *all_sources
          packages:
            - ['clang-5.0', 'libstdc++-8-dev']
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"        
      

before_install:
  - eval "${MATRIX_EVAL}"

script: 
  - cmake --version
  - mkdir build && cd build && cmake .. && make -j $(nproc)
  - ctest