language: cpp
dist: xenial
compiler:
  - gcc  

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - g++-7
script: 
  - export CC=gcc-7
  - export CXX=g++-7
  - mkdir build && cd build && cmake .. && make -j $(nproc)