language: cpp
dist: xenial

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
      

before_install:
  - eval "${MATRIX_EVAL}"

script: 
  - cmake --version
  - mkdir build && cd build && cmake .. && make -j $(nproc)
  - ctest