language: cpp
dist: xenial

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - ['clang-6.0', 'libstdc++6-dev']
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
      

before_install:
  - eval "${MATRIX_EVAL}"

script: 
  - cmake --version
  - mkdir build && cd build && cmake .. && make -j $(nproc)
  - ctest